name: 経費申請
description: Zli の経費精算を申請します
title: "[Expense] {{date}} {{applicant}} - ¥{{total}}"
labels: ["expense", "pending-review"]
assignees: ["finance-team"]

body:
  - type: input
    id: applicant
    attributes:
      label: 申請者（GitHub ID）
      placeholder: shota-sakuyama
    validations: {required: true}

  - type: input
    id: date
    attributes:
      label: 支出日 (YYYY-MM-DD)
      placeholder: "2025-05-15"
    validations: {required: true, pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"}

  - type: textarea
    id: items
    attributes:
      label: 明細
      description: |
        1行につき1項目。書式: <カテゴリ>\t<内容>\t<金額>
      placeholder: |
        交通費    会津大学→郡山駅    2640
        お弁当    LT準備スタッフ弁当  850
    validations: {required: true}

  - type: input
    id: total
    attributes:
      label: 合計金額 (円)
      placeholder: "3490"
    validations: {required: true}

  - type: textarea
    id: receipts
    attributes:
      label: 領収書・レシート画像
      description: 画像をドラッグ & ドロップ、またはクラウドの共有リンクを貼付けてください
